### ISSUE TITLE
Revert to use of version 3 of the NUnit engine API

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/net20-pluggable-agent#21]
The extension was developed using the NUnit Engine development branch but version 4 is not likely to come out soon so we should use a production version. This may be as simple as just changing the package references or it may introduce further problems to resolve.

The most likely problem has to do with a change in the semantics of the TestPackage constructor between the NUnit 3 and 4 APIs.

**Comment by YashUoM** [comment]
Update: Starting with this one

**Comment by YashUoM** [comment]
Hi Charlie, 

Can you elaborate this little more?

**Comment by CharliePoole** [comment]
@YashUoM 

Sure... first step, of course, will be to find and change all references to `nunit.engine.api` 4.0.0-dev00102 to 3.16.2. This will be primarily in the project files but also check build.cake just in case.

While you are at it, you should probably also update all references to the testcentric engine to the latest dev version on MyGet.org, which is currently 2.0.0-dev00033.

With the TestPackage constructor, you will need to change any `new TestPackage(file)` specifying a single file argument to `new TestPackage(new [] { file })`. Most of these will be in the tests.

**Comment by CharliePoole** [comment]
@YashUoM Yet another small "while you are at it" task in this extension...

The tools directory contains multiple assemblies but only one of them implements the extension. But the engine has to examine all of them, which is inefficient. If the tools directory contained a `*.addins` file pointing to the correct assembly, then only that one would be examined. 

The addins file can be named anything, e.g. `net20-pluggable-agent.addins` and should contain one line with `net20-agent-launcher.dll`. When the engine examines a directory containing a `*.addins` file or files, it __only__ looks at the content of those files and doesn't look at other assemblies in the same directory.

Please treat this as an "extra" and skip it if you need to.

**Comment by CharliePoole** [comment]
FYI I just released testcentric engine 2.0.0-alpha7. Use that for any testcentric engine references. No release of the Gui itself yet, but coming soon.
